package com.helger.peppol.validation.supplementary.createrules;

import java.io.File;

import org.w3c.dom.Document;

import com.helger.commons.io.file.FilenameHelper;
import com.helger.commons.io.file.SimpleFileIO;
import com.helger.commons.io.resource.FileSystemResource;
import com.helger.commons.microdom.IMicroElement;
import com.helger.commons.microdom.serialize.MicroReader;
import com.helger.commons.xml.namespace.MapBasedNamespaceContext;
import com.helger.commons.xml.serialize.write.XMLWriter;
import com.helger.commons.xml.serialize.write.XMLWriterSettings;
import com.helger.peppol.validation.supplementary.createrules.util.CreateHelper;
import com.helger.schematron.xslt.ISchematronXSLTBasedProvider;
import com.helger.schematron.xslt.SCHTransformerCustomizer;
import com.helger.schematron.xslt.SchematronResourceSCHCache;

/**
 * Create the XSLTs for the BIICORE Schematrons. This only needs to be invoked
 * when the BIICORE Schematron files change. There is no real dependency to the
 * other tools except that {@link Main4CreateValidationRules} uses the XSLT file
 * generated by this tool to copy it to the respective folder.
 *
 * @author Philip Helger
 */
public final class Main3CreateBIICoreXSLT
{
  public static void main (final String [] args)
  {
    for (final ERuleSource eRuleSource : ERuleSource.values ())
      if (eRuleSource.hasBIICoreFile ())
      {
        final File aSCHFile = eRuleSource.getBIICoreSchematronFile ();
        {
          CreateHelper.log ("Creating XSLT for " + aSCHFile.getName ());

          final FileSystemResource aSCHRes = new FileSystemResource (aSCHFile);
          final ISchematronXSLTBasedProvider aXSLTProvider = SchematronResourceSCHCache.createSchematronXSLTProvider (aSCHRes,
                                                                                                                      new SCHTransformerCustomizer ());
          if (aXSLTProvider == null)
          {
            // Error message already emitted!
            continue;
          }
          final Document aXSLTDoc = aXSLTProvider.getXSLTDocument ();

          final MapBasedNamespaceContext aNSCtx = new MapBasedNamespaceContext ();
          aNSCtx.addMapping ("xsl", "http://www.w3.org/1999/XSL/Transform");
          aNSCtx.addMapping ("svrl", "http://purl.oclc.org/dsdl/svrl");
          // Read all mappings from Schematron file
          for (final IMicroElement aElement : MicroReader.readMicroXML (aSCHRes)
                                                         .getDocumentElement ()
                                                         .getAllChildElements ("ns"))
            aNSCtx.addMapping (aElement.getAttributeValue ("prefix"), aElement.getAttributeValue ("uri"));

          final XMLWriterSettings aXWS = new XMLWriterSettings ().setNamespaceContext (aNSCtx)
                                                                 .setPutNamespaceContextPrefixesInRoot (true);

          final File aXSLTFile = new File (FilenameHelper.getWithoutExtension (aSCHFile.getPath ()) + ".xslt");
          if (SimpleFileIO.writeFile (aXSLTFile, XMLWriter.getNodeAsString (aXSLTDoc, aXWS), aXWS.getCharsetObj ())
                          .isFailure ())
            throw new IllegalStateException ("Failed to write " + aXSLTFile);
        }
      }
  }
}
